# Generated by Django 3.2.25 on 2025-04-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('ename', models.CharField(max_length=21)),
                ('sal', models.FloatField()),
                ('company', models.CharField(max_length=21)),
            ],
        ),
    ]
