# Generated by Django 5.2 on 2025-05-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=21)),
                ('price', models.FloatField()),
                ('brand', models.CharField(max_length=21)),
            ],
        ),
    ]
