# Generated by Django 5.2 on 2025-05-10 10:29

import application1.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=21, validators=[application1.validators.validate_name])),
                ('roll_no', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('std', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('marks', models.PositiveIntegerField(validators=[application1.validators.validate_marks])),
                ('nick_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(15)])),
                ('phone_no', models.PositiveBigIntegerField(validators=[application1.validators.validate_phone_no])),
            ],
        ),
    ]
