# Generated by Django 3.2.25 on 2025-04-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('pname', models.CharField(max_length=21)),
                ('price', models.FloatField()),
                ('company', models.CharField(max_length=21)),
            ],
        ),
    ]
