# Generated by Django 3.2.25 on 2025-04-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginDetails',
            new_name='Login',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='login',
            new_name='username',
        ),
    ]
