# Generated by Django 5.2 on 2025-05-12 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=21)),
                ('phone_no', models.PositiveBigIntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('detailsmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app3.detailsmodel')),
                ('roll_no', models.PositiveSmallIntegerField()),
                ('standard', models.IntegerField()),
            ],
            bases=('app3.detailsmodel',),
        ),
    ]
