# Generated by Django 5.2 on 2025-05-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=23)),
                ('roll_no', models.PositiveSmallIntegerField()),
                ('standard', models.CharField(max_length=21)),
            ],
        ),
    ]
