# Generated by Django 5.2 on 2025-05-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=21)),
                ('movie_frame', models.ImageField(upload_to='images/')),
                ('budget', models.FloatField()),
                ('hero', models.CharField(max_length=21)),
                ('director', models.CharField(max_length=21)),
                ('description', models.CharField(default='No description available', max_length=300)),
                ('rating', models.CharField(max_length=21)),
            ],
        ),
        migrations.CreateModel(
            name='web_series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=21)),
                ('photo', models.ImageField(upload_to='images/')),
                ('budget', models.FloatField()),
                ('hero', models.CharField(max_length=21)),
                ('director', models.CharField(max_length=21)),
                ('description', models.CharField(default='No description available', max_length=300)),
                ('rating', models.CharField(max_length=21)),
            ],
        ),
    ]
