# Generated by Django 5.2 on 2025-05-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='budget',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='movies',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='web_series',
            name='budget',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='web_series',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
