# Generated by Django 5.2 on 2025-05-07 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0002_alter_movies_budget_alter_movies_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
