# Generated by Django 5.2 on 2025-05-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0003_movies_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='web_series',
            name='series_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
