# Generated by Django 5.2 on 2025-05-07 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0004_movies_movie_id_web_series_series_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=21)),
                ('movie_frame', models.ImageField(upload_to='images/')),
                ('budget', models.CharField(max_length=21)),
                ('hero', models.CharField(max_length=21)),
                ('director', models.CharField(max_length=21)),
                ('description', models.CharField(default='No description available', max_length=300)),
                ('rating', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='movies',
        ),
        migrations.RemoveField(
            model_name='web_series',
            name='id',
        ),
        migrations.AlterField(
            model_name='web_series',
            name='series_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
