# Generated by Django 5.2 on 2025-05-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0005_movie_delete_movies_remove_web_series_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='movie',
            new_name='movies',
        ),
    ]
