# Generated by Django 5.2 on 2025-05-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0006_rename_movie_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='web_series',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='web_series',
            name='series_id',
            field=models.IntegerField(),
        ),
    ]
