# Generated by Django 5.2 on 2025-05-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=21)),
                ('phone_no', models.PositiveBigIntegerField()),
                ('address', models.TextField()),
                ('roll_no', models.PositiveSmallIntegerField()),
                ('standard', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=21)),
                ('phone_no', models.PositiveBigIntegerField()),
                ('address', models.TextField()),
                ('subject', models.CharField(max_length=21)),
                ('salary', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
