# Generated by Django 3.2.25 on 2025-04-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='std',
            name='address',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='std',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
