# Generated by Django 3.2.25 on 2025-04-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=21)),
                ('stu_rollno', models.IntegerField()),
                ('stu_addr', models.CharField(max_length=21)),
                ('stu_phone', models.IntegerField()),
                ('standard', models.PositiveIntegerField()),
                ('sub1', models.PositiveIntegerField()),
                ('sub2', models.PositiveIntegerField()),
                ('sub3', models.PositiveIntegerField()),
                ('sub4', models.PositiveIntegerField()),
                ('sub5', models.PositiveIntegerField()),
            ],
        ),
    ]
