# Generated by Django 5.2 on 2025-05-11 05:35

import application1.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20, validators=[application1.validators.validate_name])),
                ('roll_no', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('phone_no', models.PositiveBigIntegerField(validators=[application1.validators.validate_phone])),
                ('standard', models.TextField()),
                ('sub1', models.PositiveIntegerField(validators=[application1.validators.validate_marks])),
                ('sub2', models.PositiveIntegerField(validators=[application1.validators.validate_marks])),
                ('sub3', models.PositiveIntegerField(validators=[application1.validators.validate_marks])),
                ('sub4', models.PositiveIntegerField(validators=[application1.validators.validate_marks])),
                ('sub5', models.PositiveIntegerField(validators=[application1.validators.validate_marks])),
            ],
        ),
    ]
