# Generated by Django 5.2 on 2025-05-11 05:49

import application1.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=21, validators=[application1.validators.validate_username])),
                ('password', models.CharField(max_length=21, validators=[application1.validators.validate_password])),
            ],
        ),
    ]
