# Generated by Django 3.2.25 on 2025-04-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pid', models.IntegerField()),
                ('Pname', models.CharField(max_length=21)),
                ('Price', models.FloatField()),
                ('Company', models.CharField(max_length=21)),
                ('M_date', models.DateField()),
                ('Exp_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cid', models.IntegerField()),
                ('Cname', models.CharField(max_length=21)),
                ('Address', models.CharField(max_length=21)),
                ('Mobile_Number', models.CharField(max_length=21)),
                ('Email_Address', models.EmailField(max_length=254)),
                ('product', models.ManyToManyField(to='application1.Products')),
            ],
        ),
    ]
