# Generated by Django 3.2.25 on 2025-04-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=21)),
                ('phone_no', models.PositiveIntegerField()),
                ('standard', models.PositiveIntegerField()),
                ('sub1', models.PositiveIntegerField()),
                ('sub2', models.PositiveIntegerField()),
                ('sub3', models.PositiveIntegerField()),
                ('sub4', models.PositiveIntegerField()),
                ('sub5', models.PositiveIntegerField()),
            ],
        ),
    ]
