# Generated by Django 3.2.25 on 2025-04-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='roll_no',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
