# Generated by Django 3.2.25 on 2025-04-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0002_studentmodel_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
