# Generated by Django 5.2 on 2025-05-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField()),
                ('name', models.CharField(max_length=21)),
                ('stu_class', models.CharField(max_length=21)),
                ('phone_no', models.IntegerField()),
                ('address', models.CharField()),
            ],
        ),
    ]
