# Generated by Django 3.2.25 on 2025-04-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersDeatils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=21)),
                ('last_name', models.CharField(max_length=21)),
                ('username', models.CharField(max_length=21)),
                ('p1', models.CharField(max_length=21)),
                ('p2', models.CharField(max_length=21)),
                ('mobile_no', models.CharField(max_length=21)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
