# Generated by Django 3.2.25 on 2025-04-27 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=21)),
                ('Last_Name', models.CharField(max_length=21)),
                ('Username', models.CharField(max_length=21)),
                ('P1', models.CharField(max_length=21)),
                ('P2', models.CharField(max_length=21)),
                ('Mobile_Number', models.CharField(max_length=21)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Atricle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=29)),
                ('public_date', models.DateField()),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application1.reporters')),
            ],
        ),
    ]
